PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nama TEXT NOT NULL,
  username TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL CHECK(role IN ('admin', 'auditor', 'auditee')),
  avatar TEXT NOT NULL DEFAULT 'US',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS standar (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nama TEXT NOT NULL,
  urutan INTEGER NOT NULL DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS indikator (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  standar_id INTEGER NOT NULL REFERENCES standar(id) ON DELETE CASCADE,
  kode TEXT NOT NULL,
  deskripsi TEXT NOT NULL,
  urutan INTEGER NOT NULL DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS prodi (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  kode TEXT NOT NULL UNIQUE,
  nama TEXT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS periode (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nama TEXT NOT NULL,
  aktif INTEGER NOT NULL DEFAULT 0 CHECK(aktif IN (0, 1)),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS skor_config (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nilai INTEGER NOT NULL,
  label TEXT NOT NULL,
  warna TEXT NOT NULL DEFAULT '#6B7280',
  bg_warna TEXT NOT NULL DEFAULT '#F3F4F6'
);

CREATE TABLE IF NOT EXISTS app_config (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  key TEXT NOT NULL UNIQUE,
  value TEXT NOT NULL,
  label TEXT,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS instrumen (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  indikator_id INTEGER NOT NULL REFERENCES indikator(id) ON DELETE CASCADE,
  prodi_id INTEGER NOT NULL REFERENCES prodi(id),
  periode_id INTEGER NOT NULL REFERENCES periode(id),
  auditor1_id INTEGER REFERENCES users(id),
  auditor2_id INTEGER REFERENCES users(id),
  auditee_id INTEGER REFERENCES users(id),
  status TEXT NOT NULL DEFAULT 'belum' CHECK(status IN ('belum', 'diisi', 'proses', 'selesai')),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS evaluasi_auditee (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  instrumen_id INTEGER NOT NULL REFERENCES instrumen(id) ON DELETE CASCADE,
  periode_id INTEGER NOT NULL REFERENCES periode(id),
  prodi_id INTEGER NOT NULL REFERENCES prodi(id),
  user_id INTEGER NOT NULL REFERENCES users(id),
  skor INTEGER CHECK(skor BETWEEN 0 AND 4),
  catatan TEXT,
  file_path TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS hasil_audit (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  instrumen_id INTEGER NOT NULL REFERENCES instrumen(id) ON DELETE CASCADE,
  periode_id INTEGER NOT NULL REFERENCES periode(id),
  prodi_id INTEGER NOT NULL REFERENCES prodi(id),
  auditor_id INTEGER NOT NULL REFERENCES users(id),
  skor INTEGER CHECK(skor BETWEEN 0 AND 4),
  catatan TEXT,
  rekomendasi TEXT,
  perlu_rtl INTEGER NOT NULL DEFAULT 0 CHECK(perlu_rtl IN (0, 1)),
  status TEXT DEFAULT 'sesuai',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tindak_lanjut (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  instrumen_id INTEGER NOT NULL REFERENCES instrumen(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(id),
  deskripsi TEXT NOT NULL,
  file_path TEXT,
  status TEXT NOT NULL DEFAULT 'belum' CHECK(status IN ('belum', 'dilaksanakan', 'diverifikasi')),
  verified_by INTEGER REFERENCES users(id),
  verified_at DATETIME,
  catatan_verifikasi TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);